add functionality to only run relevant channels in data and embedded
KIT-CMS/KITHiggsToTauTau pull request #19
Opened 2019-06-03 09:38 UTC by swozniewski

Artur und ich hatten es davon, dass es sinnvoll wäre, bei Daten (bei embedded vmtl auch) nur die tatsächlich verwendeten channels in Artus zu prozessieren. Das würde insbesondere dem friend-tree-producer helfen, nur sinnvolle jobs abzuschicken. Schaut bitte mal auf diese filter-Funktion in der Artus-Config, ob die so ok ist und ob ihr generell mit dieser Änderung einverstanden seid.

2019-06-03 09:39 UTC, harrypuuter commented
Mega die gute Idee !

2019-06-03 09:44 UTC, janekbechtel commented
:+1: find ich gut

2019-06-03 09:44 UTC, janekbechtel approved these changes

2019-06-03 09:45 UTC, harrypuuter commented
Theoretisch könnte man SingleElectron auch in ee brauchen und SingeMuon in mm ? Aber das ist auch eher theoretischer Natur

2019-06-03 09:45 UTC, janekbechtel commented
ah noch ein Typo bei mt:      elif re.search("(SingleMuon|*MuTauFinalState*)", nickname):

2019-06-03 09:47 UTC, harrypuuter approved these changes

2019-06-03 09:47 UTC, janekbechtel approved these changes

2019-06-03 21:17 UTC, ArturAkh commented on python/data/ArtusConfigs/Run2LegacyAnalysis_base.py
> +    elif re.search("(SingleElectron|ElTauFinalState)", nickname):
For 2018, you would need to write `EGamma` additionaly

2019-06-03 21:22 UTC, ArturAkh requested changes
Please add the change needed for 2018 in case of et.

About `mm` and `ee` channels: I agree with Sebastian B., that also SingleMuon & SingleElectron datasets are processed in these channels.

So you would need to add `mm` and `ee` in case of these datasets

2019-06-03 21:23 UTC, ArturAkh commented on python/data/ArtusConfigs/Run2LegacyAnalysis_base.py
> +    elif re.search("(SingleMuon|MuTauFinalState)", nickname):
In case of SingleMuon, please add `mm`

2019-06-03 21:24 UTC, ArturAkh commented on python/data/ArtusConfigs/Run2LegacyAnalysis_base.py
> +    elif re.search("(SingleElectron|ElTauFinalState)", nickname):
And add also in case of SingleElectron|EGamma the `ee` channel

2019-06-04 16:09 UTC, ArturAkh approved these changes

2019-06-04 16:10 UTC, merged